#! /usr/bin/python
"""
print_model.py -- Utility script for dumping information on a TinySR speech model.
"""

import struct, sys

if len(sys.argv) == 1:
	print "Usage: print_model.py speech_model [speech_model ...]"
	print "Prints basic info on a speech model as generated by model_gen.py."
	exit(1)

for path in sys.argv[1:]:
	with open(path) as f:
		print "Model: %r" % path
		while True:
			s = f.read(4)
			if not s: break
			name_length, = struct.unpack("<I", s)
			name = f.read(name_length)
			ll_offset, ll_slope = struct.unpack("<2f", f.read(8))
			utterance_length, = struct.unpack("<I", f.read(4))
			print "  Word: %-10r (%i ms) (%7.3f + %5.3f * LL)" % (name, utterance_length * 10, ll_offset, ll_slope)
			# Constant comes from: 1 float for ll offset, 13 floats for mean, 13*13 floats for covariance.
			f.read(utterance_length * (1 + 13 + 13*13) * 4)

